[toolchain]
# Use the stable Rust toolchain (you switched from nightly and want consistency).
channel = "stable"

# Keep it minimal; add components that are commonly needed for CI / linting / formatting.
components = [
    "rustfmt",
    "clippy"
]

# Primary compilation target (Windows MSVC). Add others if you routinely cross-compile.
targets = [
    "x86_64-pc-windows-msvc"
]

# Optional: Uncomment to freeze to a specific stable version once you validate it works well
# (prevents sudden regressions when a new stable is released).
# channel = "1.78.0"

# Notes:
# - This file ensures every developer and CI use the same stable toolchain.
# - If rust-analyzer was previously loading a cached nightly proc-macro server, a
#   full `cargo clean` + editor restart may be needed after adding this file.
