[workspace]

[package]
name = "veil-validation-tools"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "validate_grammar"
path = "validate_grammar.rs"

[dependencies]
pest = "2.8.1"
pest_meta = "2.8.1"
